apiVersion: app/latest
kind: Deployment
metadata:
  name: vprodb
  lables: 
    app:vprodb
spec:
  selector:
    matchlabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      lables:
        app: vprodb
    spec:
      containers:
        - name: vprodb
          image: 
          volumesMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data
          ports:
            - name: vprodb-port
              containerPort: 3306
          env:
           - name: MYSQL_ROOT_PASSWORD
             valueFrom:
               secretKeyRef:
                  name: app-secret
                  key: db-pass
      nodeSelectors:
         zone: us-east-1a
      volumes:
        - name: vpro-db-data
          awsElasticBlockStore:
              volumeID:  vol-0afc64ad222ed3248
              fsType: ext4
      
      initContainers:
          - name: busybox
            image: busybox:latest
            args: ["rm","-rf","/var/lib/mysql/lost+found"]
            volumesMounts:
              - name: vpro-db-data
                mountPath: /var/lib/mysql
